# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CSE 340 notes
tagline:          ''
description:      'A compilation of notes for CSE 340: Interaction Programming at UW Seattle.'
url:              "https://jetplanejj.github.io"
baseurl:          /

author:
  name:           'Jay Lin'
  url:            "https://jetplanejj.github.io"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           "https://github.com/JetPlaneJJ"
