# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            CSE 340 notes
tagline:          ''
description:      'A compilation of notes for CSE 340: Interaction Programming at UW Seattle.'
url:              https://github.com/JetPlaneJJ
baseurl:          /

author:
  name:           'Jay Lin'
  url:            https://github.com/JetPlaneJJ

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JetPlaneJJ
